### ISSUE TITLE
[suggestion] give a redstone pluse in the back when block is mined.

### ISSUE THREAD

**Issue by AiDSl** [JoshiCodes/BlockBreakerMod#1]
so it can work with flying machine better :>

**Comment by JoshiCodes** [comment]
So sorry, didnt see your Issue! As I'm unfortunately no longer working on this project, it may take a while, but I'll get to it.
Thank you for your suggestion :)

**Comment by JoshiCodes** [comment]
Implemented in the [Latest Release 1.19.2-1.0.2.0](https://github.com/JoshiCodes/BlockBreakerMod/releases/latest)!
See b38f003 and 745f44c for more infos.
